# exampleSite/config.yaml
baseURL: https://japerre.github.io/personal-website/ # Replace with your domain
canonifyURLS: true
languageCode: en-us
theme: smigle
# themesDir: /themes # Only needed for running the example site
title: Tibo Laperre
menu:
  main: # Change menu as needed
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
    - identifier: rss
      name: RSS
      url: /index.xml
      weight: 6
params:
  abbrDateFmt: "Jan 2"
  author: "Tibo Laperre"
  # brandIconFile: "images/brandIcon.svg"
  brandIconFile: "images/profielfoto_very_cropped.jpg"
  dateFmt: "2006-01-02"
  ##
  ## Options for overriding theme or page defaults
  ##
  #customStylesheets: # Use to override theme styles, like logo size
  #  - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range
  social:
    - name: GitHub
      url: https://github.com/Japerre
    - name: LinkedIN
      url: https://www.linkedin.com/in/tibo-laperre-b97525252/
  subtitle: "another Belgian on the internet"
